server:
  port: 8080

product:
  client:
    urls:
      ms-product: ${MS_PRODUCT_URL:http://ms-product:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}


  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}


  redisson:
    single-server-config:
      address: ${REDIS_URL:redis://localhost:6379}


cart:
  recommendation:
    cron: "0 0/30 * * * *"